# Generated by Django 5.1.6 on 2025-08-03 00:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import user_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('phone_number', models.CharField(error_messages={'null': 'شماره تلفن کاربر باید وارد شود'}, max_length=11, validators=[user_module.models.phone_validator], verbose_name='شماره تلفن')),
                ('national_number', models.CharField(error_messages={'null': 'شماره ملی کاربر باید وارد شود', 'unique': 'کاربری با این شماره ملی قبلا ثبت نام کرده است'}, max_length=10, unique=True, validators=[user_module.models.nat_number_validator], verbose_name='شماره ملی کاربر (ضروری)')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='زمان ساخت حساب کاربری')),
                ('user_type', models.CharField(choices=[('دانشجو', 'دانشجو'), ('استاد', 'استاد'), ('کارمند یا کارشناس', 'کارمند یا کارشناس')], default='دانشجو', error_messages={'null': 'نوع کاربر باید مشخص باشد'}, max_length=20, verbose_name='نوع کاربر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='تصویر کاربر')),
                ('area_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='کد محل فعالیت')),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('نامشخص', 'نامشخص')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='جنسیت')),
                ('latest_degree', models.CharField(choices=[('کارشناسی پیوسته', 'کارشناسی پیوسته'), ('کارشناسی ناپیوسته', 'کارشناسی ناپیوسته'), ('کاردانی پیوسته', 'کاردانی پیوسته'), ('کاردانی ناپیوسته', 'کاردانی ناپیوسته'), ('کارشناسی ارشد ناپیوسته', 'کارشناسی ارشد ناپیوسته'), ('دکتری حرفه ای', 'دکتری حرفه ای'), ('دکتری مستقیم', 'دکتری مستقیم'), ('کارشناسی ارشد پیوسته', 'کارشناسی ارشد پیوسته')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name=' آخرین مقطع تحصیلی')),
                ('latest_certificate_picture', models.ImageField(error_messages={'null': 'این فیلد باید مشخص شود'}, upload_to='students_certs', verbose_name='تصویر مدرک آخرین مقطع تحصیلی ')),
                ('latest_degree_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=25, verbose_name='کد رشته آخرین مقطع تحصیلی')),
                ('department', models.CharField(choices=[('مهندسی', 'مهندسی'), ('علوم پایه', 'علوم پایه'), ('علوم انسانی', 'علوم انسانی'), ('علوم پزشکی', 'علوم پزشکی'), ('هنر', 'هنر'), ('تربیت بدنی', 'تربیت بدنی')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name='دانشکده محل فعالیت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='آیا این پروفایل تایید شده است یا خیر؟')),
                ('approval_document', models.ImageField(blank=True, null=True, upload_to='profile_approvals', verbose_name='اسکن مدرک تایید پروفایل')),
                ('role', models.CharField(choices=[('کارشناس آموزش', 'کارشناس آموزش'), ('کارشناس گروه', 'کارشناس گروه')], default='عادی', max_length=30, verbose_name='نقش کارمند')),
                ('user', models.OneToOneField(error_messages={'null': 'این فیلد باید مشخص شود'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='این اطلاعات مربوط به کدام کارمند می باشد')),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'latest_degree_code'], name='index combo for employees')],
            },
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='تصویر کاربر')),
                ('area_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='کد محل فعالیت')),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('نامشخص', 'نامشخص')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='جنسیت')),
                ('latest_degree', models.CharField(choices=[('کارشناسی پیوسته', 'کارشناسی پیوسته'), ('کارشناسی ناپیوسته', 'کارشناسی ناپیوسته'), ('کاردانی پیوسته', 'کاردانی پیوسته'), ('کاردانی ناپیوسته', 'کاردانی ناپیوسته'), ('کارشناسی ارشد ناپیوسته', 'کارشناسی ارشد ناپیوسته'), ('دکتری حرفه ای', 'دکتری حرفه ای'), ('دکتری مستقیم', 'دکتری مستقیم'), ('کارشناسی ارشد پیوسته', 'کارشناسی ارشد پیوسته')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name=' آخرین مقطع تحصیلی')),
                ('latest_certificate_picture', models.ImageField(error_messages={'null': 'این فیلد باید مشخص شود'}, upload_to='students_certs', verbose_name='تصویر مدرک آخرین مقطع تحصیلی ')),
                ('latest_degree_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=25, verbose_name='کد رشته آخرین مقطع تحصیلی')),
                ('department', models.CharField(choices=[('مهندسی', 'مهندسی'), ('علوم پایه', 'علوم پایه'), ('علوم انسانی', 'علوم انسانی'), ('علوم پزشکی', 'علوم پزشکی'), ('هنر', 'هنر'), ('تربیت بدنی', 'تربیت بدنی')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name='دانشکده محل فعالیت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='آیا این پروفایل تایید شده است یا خیر؟')),
                ('approval_document', models.ImageField(blank=True, null=True, upload_to='profile_approvals', verbose_name='اسکن مدرک تایید پروفایل')),
                ('student_number', models.TextField()),
                ('average', models.FloatField(blank=True, null=True, verbose_name='معدل دانشجو')),
                ('degree', models.CharField(choices=[('کارشناسی پیوسته', 'کارشناسی پیوسته'), ('کارشناسی ناپیوسته', 'کارشناسی ناپیوسته'), ('کاردانی پیوسته', 'کاردانی پیوسته'), ('کاردانی ناپیوسته', 'کاردانی ناپیوسته'), ('کارشناسی ارشد ناپیوسته', 'کارشناسی ارشد ناپیوسته'), ('دکتری حرفه ای', 'دکتری حرفه ای'), ('دکتری مستقیم', 'دکتری مستقیم'), ('کارشناسی ارشد پیوسته', 'کارشناسی ارشد پیوسته')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=40, verbose_name=' مقطع تحصیلی فعلی')),
                ('status', models.CharField(choices=[('عادی', 'عادی'), ('اخراج', 'اخراج'), ('مرخصی', 'مرخصی'), ('فارغ التحصیل', 'فارغ التحصیل')], default='عادی', error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=40, verbose_name='وضعیت دانشجو')),
                ('current_degree_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=25, verbose_name='کد رشته  مقطع تحصیلی فعلی')),
                ('user', models.OneToOneField(error_messages={'null': 'کاربر مربوطه باید مشخص بشود'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'degree', 'current_degree_code'], name=' index for studetns')],
            },
        ),
        migrations.CreateModel(
            name='Teacher_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='تصویر کاربر')),
                ('area_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='کد محل فعالیت')),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('نامشخص', 'نامشخص')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='جنسیت')),
                ('latest_degree', models.CharField(choices=[('کارشناسی پیوسته', 'کارشناسی پیوسته'), ('کارشناسی ناپیوسته', 'کارشناسی ناپیوسته'), ('کاردانی پیوسته', 'کاردانی پیوسته'), ('کاردانی ناپیوسته', 'کاردانی ناپیوسته'), ('کارشناسی ارشد ناپیوسته', 'کارشناسی ارشد ناپیوسته'), ('دکتری حرفه ای', 'دکتری حرفه ای'), ('دکتری مستقیم', 'دکتری مستقیم'), ('کارشناسی ارشد پیوسته', 'کارشناسی ارشد پیوسته')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name=' آخرین مقطع تحصیلی')),
                ('latest_certificate_picture', models.ImageField(error_messages={'null': 'این فیلد باید مشخص شود'}, upload_to='students_certs', verbose_name='تصویر مدرک آخرین مقطع تحصیلی ')),
                ('latest_degree_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=25, verbose_name='کد رشته آخرین مقطع تحصیلی')),
                ('department', models.CharField(choices=[('مهندسی', 'مهندسی'), ('علوم پایه', 'علوم پایه'), ('علوم انسانی', 'علوم انسانی'), ('علوم پزشکی', 'علوم پزشکی'), ('هنر', 'هنر'), ('تربیت بدنی', 'تربیت بدنی')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name='دانشکده محل فعالیت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='آیا این پروفایل تایید شده است یا خیر؟')),
                ('approval_document', models.ImageField(blank=True, null=True, upload_to='profile_approvals', verbose_name='اسکن مدرک تایید پروفایل')),
                ('rank', models.CharField(choices=[('استادیار', 'استادیار'), ('دانشیار', 'دانشیار'), ('استاد تمام', 'استاد تمام')], error_messages={'null': 'مرتبه علمی استاد باید مشخص شود'}, max_length=30, verbose_name='مرتبه علمی استاد')),
                ('role', models.CharField(choices=[('مدیر گروه', 'مدیر گروه'), ('مسوول پژوهشی', 'مسوول پژوهشی'), ('رییس دانشکده', 'رییس دانشکده'), ('عادی', 'عادی')], default='عادی', max_length=25, verbose_name='نقش استاد')),
                ('is_faculty', models.BooleanField(default=False, verbose_name='آیا استاد مربوطه عضو هیت علمی می باشد؟')),
                ('user', models.OneToOneField(error_messages={'null': 'این فیلد باید مشخص شود'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='این اطلاعات مربوط به کدام استاد می باشد')),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'rank', 'latest_degree_code'], name='index combo for teachers')],
            },
        ),
    ]
