# Generated by Django 5.1.6 on 2025-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان خبر(حداکثر 300 کاراکتر)')),
                ('content', models.TextField(verbose_name='متن اصلی خبر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد خبر')),
                ('thumbnail', models.ImageField(upload_to='news_thumbs')),
            ],
        ),
    ]
