# Generated by Django 5.1.6 on 2025-11-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('انتخاب واحد', 'انتخاب واحد'), ('ترم آخری', 'ترم آخری'), ('انتخاب واحد خارج از بازه', 'انتخاب واحد خارج از بازه'), ('سنوات', 'سنوات')], max_length=40, verbose_name='نوع مجوز')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد مجوز')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تیید شده')),
            ],
        ),
    ]
