# Generated by Django 5.1.6 on 2025-08-17 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester_module', '0002_current_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('انتخاب واحد', 'انتخاب واحد'), ('ترم آخری', 'ترم آخری'), ('انتخاب واحد خارج از بازه', 'انتخاب واحد خارج از بازه'), ('سنوات', 'سنوات'), ('انتخاب 24 واحد', 'انتخاب 24 واحد')], max_length=40, verbose_name='نوع مجوز')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد مجوز')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تیید شده')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست کننده مجوز')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='semester_module.semester', verbose_name='نیمسال مربوطه')),
            ],
            options={
                'indexes': [models.Index(fields=['semester', 'creator'], name='semester and creator index')],
                'constraints': [models.UniqueConstraint(fields=('semester', 'creator', 'permit_type'), name='semester and creator uniquness', violation_error_message='این کاربر در حال حاضر مجوزی بااین عنوان در این نیمسال دارد')],
            },
        ),
    ]
