# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits_module', '0001_initial'),
        ('semester_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست کننده مجوز'),
        ),
        migrations.AddField(
            model_name='permit',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='semester_module.semester', verbose_name='نیمسال مربوطه'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['semester', 'creator'], name='semester and creator index'),
        ),
        migrations.AddConstraint(
            model_name='permit',
            constraint=models.UniqueConstraint(fields=('semester', 'creator', 'permit_type'), name='semester and creator uniquness', violation_error_message='این کاربر در حال حاضر مجوزی بااین عنوان در این نیمسال دارد'),
        ),
    ]
