# Generated by Django 5.1.6 on 2025-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(choices=[('انتخاب واحد', 'انتخاب واحد'), ('ترم آخری', 'ترم آخری'), ('انتخاب واحد خارج از بازه', 'انتخاب واحد خارج از بازه'), ('سنوات', 'سنوات')], max_length=40, verbose_name='نوع مجوز'),
        ),
    ]
