# Generated by Django 5.1.6 on 2025-08-29 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.TextField(verbose_name='متن سوال')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('ضعیف', 'ضعیف'), ('خیلی ضعیف', 'خیلی ضعیف')], default='متوسط', max_length=20, verbose_name='نظر کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_module.review_question', verbose_name='سوال')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_module.review_session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='review_session',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='check student and teacher pair uniquness', violation_error_message='این دانشجو قبلا مدلی برای امتیاز دهی به این استاد ایجاد کرده است'),
        ),
    ]
