# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.TextField(verbose_name='متن سوال')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('ضعیف', 'ضعیف'), ('خیلی ضعیف', 'خیلی ضعیف')], default='متوسط', max_length=20, verbose_name='نظر کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_closed', models.BooleanField(default=False, verbose_name='نظر سنجی تایید نهایی شده است یا خیر؟')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_reviews', to='semester_module.semester')),
            ],
        ),
    ]
