# Generated by Django 5.1.6 on 2025-08-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_session',
            name='session_closed',
            field=models.BooleanField(default=False, verbose_name='نظر سنجی تایید نهایی شده است یا خیر؟'),
        ),
    ]
