# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review_session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review_session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviews',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_module.review_question', verbose_name='سوال'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_module.review_session'),
        ),
        migrations.AddConstraint(
            model_name='review_session',
            constraint=models.UniqueConstraint(fields=('teacher', 'student', 'semester'), name='check student and teacher pair uniquness', violation_error_message='این دانشجو قبلا مدلی برای امتیاز دهی به این استاد در این نیمسال ایجاد کرده است'),
        ),
    ]
