# Generated by Django 5.1.6 on 2025-09-01 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_module', '0002_review_session_session_closed'),
        ('semester_module', '0003_semester_semester_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_session',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_reviews', to='semester_module.semester'),
        ),
    ]
