# Generated by Django 5.1.6 on 2025-09-01 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_module', '0004_alter_review_session_semester'),
        ('semester_module', '0003_semester_semester_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review_session',
            name='check student and teacher pair uniquness',
        ),
        migrations.AlterField(
            model_name='review_session',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_reviews', to='semester_module.semester'),
        ),
        migrations.AddConstraint(
            model_name='review_session',
            constraint=models.UniqueConstraint(fields=('teacher', 'student', 'semester'), name='check student and teacher pair uniquness', violation_error_message='این دانشجو قبلا مدلی برای امتیاز دهی به این استاد در این نیمسال ایجاد کرده است'),
        ),
    ]
