# Generated by Django 5.1.6 on 2025-09-05 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_module', '0005_remove_review_session_check_student_and_teacher_pair_uniquness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='user_review',
        ),
    ]
