# Generated by Django 5.1.6 on 2025-09-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_module', '0006_rename_review_reviews_user_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_review',
            new_name='review',
        ),
    ]
