# Generated by Django 5.1.6 on 2025-09-12 17:21

import django.db.models.deletion
import ticket_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'null': 'عنوان تیک باید نوشته شود'}, max_length=100, verbose_name='عنوان تیکت')),
                ('subject', models.CharField(choices=[('ثبت مجوز', 'ثبت مجوز'), ('انتخاب درس', 'انتخاب درس'), ('حذف درس', 'حذف درس'), ('ثبت ارزشیابی', 'ثبت ارزشیابی'), ('ثبت نمره', 'ثبت نمره'), ('تایید حساب کاربری', 'تایید حساب کاربری'), ('---', '---')], error_messages={'null': 'دسته بندی باید مشخص شود'}, max_length=50, verbose_name='دسته بندی تیکت')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد تیکت')),
                ('creator', models.ForeignKey(error_messages={'null': 'کاربر ایجاد کننده تیکت مشخص نشده است!'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده تیکت')),
            ],
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پیام')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='ticket_thumbs', validators=[ticket_module.models.ticket_image_validator], verbose_name='تصویر (اختیاری)')),
                ('ticket', models.ForeignKey(error_messages={'null': 'تیکت مربوطه می بایست مشخص باشد'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket_module.ticket', verbose_name='تیکت مربوط به پیام')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Support_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پیام')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='ticket_thumbs', validators=[ticket_module.models.ticket_image_validator], verbose_name='تصویر (اختیاری)')),
                ('is_read', models.BooleanField(default=False, verbose_name='آیا پاسخ توسط کاربر خوانده شده؟')),
                ('parent_message', models.ForeignKey(error_messages={'null': 'این فیلد باید پر شود'}, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ticket_module.user_message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
