# Generated by Django 5.1.6 on 2025-11-29 23:41

import ticket_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پیام')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='ticket_thumbs', validators=[ticket_module.models.ticket_image_validator], verbose_name='تصویر (اختیاری)')),
                ('is_read', models.BooleanField(default=False, verbose_name='آیا پاسخ توسط کاربر خوانده شده؟')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'null': 'عنوان تیک باید نوشته شود'}, max_length=100, verbose_name='عنوان تیکت')),
                ('subject', models.CharField(choices=[('ثبت مجوز', 'ثبت مجوز'), ('انتخاب درس', 'انتخاب درس'), ('حذف درس', 'حذف درس'), ('ثبت ارزشیابی', 'ثبت ارزشیابی'), ('ثبت نمره', 'ثبت نمره'), ('تایید حساب کاربری', 'تایید حساب کاربری'), ('---', '---')], error_messages={'null': 'دسته بندی باید مشخص شود'}, max_length=50, verbose_name='دسته بندی تیکت')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد تیکت')),
                ('is_closed', models.BooleanField(default=False, verbose_name='آیا تیکت بسته شده است')),
            ],
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد پیام')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='ticket_thumbs', validators=[ticket_module.models.ticket_image_validator], verbose_name='تصویر (اختیاری)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
