# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(error_messages={'null': 'کاربر ایجاد کننده تیکت مشخص نشده است!'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده تیکت'),
        ),
        migrations.AddField(
            model_name='user_message',
            name='ticket',
            field=models.ForeignKey(error_messages={'null': 'تیکت مربوطه می بایست مشخص باشد'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket_module.ticket', verbose_name='تیکت مربوط به پیام'),
        ),
        migrations.AddField(
            model_name='support_response',
            name='parent_message',
            field=models.ForeignKey(error_messages={'null': 'این فیلد باید پر شود'}, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ticket_module.user_message'),
        ),
    ]
