# Generated by Django 5.1.6 on 2025-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='آیا تیکت بسته شده است'),
        ),
    ]
