# Generated by Django 5.1.6 on 2025-08-03 00:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه')], default='شنبه', max_length=30, verbose_name='روز برگزاری')),
                ('time', models.CharField(choices=[('8-10', '8-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20')], max_length=30, verbose_name='زمان برگزاری کلاس')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره دانشجو')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد واحد درسی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درس')),
                ('course_type', models.CharField(default='نظری', max_length=50, verbose_name='نوع درس')),
                ('department', models.CharField(choices=[('مهندسی', 'مهندسی'), ('علوم پایه', 'علوم پایه'), ('علوم انسانی', 'علوم انسانی'), ('علوم پزشکی', 'علوم پزشکی'), ('هنر', 'هنر'), ('تربیت بدنی', 'تربیت بدنی')], error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=30, verbose_name='دانشکده محل برگزاری')),
                ('area_code', models.CharField(error_messages={'null': 'این فیلد باید مشخص شود'}, max_length=20, verbose_name='کد محل برگزاری کلاس')),
                ('for_degrees', models.CharField(choices=[('کارشناسی پیوسته', 'کارشناسی پیوسته'), ('کارشناسی ناپیوسته', 'کارشناسی ناپیوسته'), ('کاردانی پیوسته', 'کاردانی پیوسته'), ('کاردانی ناپیوسته', 'کاردانی ناپیوسته'), ('کارشناسی ارشد ناپیوسته', 'کارشناسی ارشد ناپیوسته'), ('دکتری حرفه ای', 'دکتری حرفه ای'), ('دکتری مستقیم', 'دکتری مستقیم'), ('کارشناسی ارشد پیوسته', 'کارشناسی ارشد پیوسته')], default='کارشناسی پیوسته', max_length=30, verbose_name='این درس برای کدام مقطع تحصیلی می باشد')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کلاس')),
                ('class_times', models.ManyToManyField(blank=True, related_name='classes', to='course_module.class_times', verbose_name='زمان های برگزاری کلاس')),
                ('requirements', models.ManyToManyField(blank=True, to='course_module.course', verbose_name='پیش نیاز ها')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='semester_module.semester', verbose_name='ترم تحصیلی مربوطه')),
            ],
        ),
    ]
