# Generated by Django 5.1.6 on 2025-08-03 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='attending_courses', to=settings.AUTH_USER_MODEL, verbose_name='دانشجویان درس'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to=settings.AUTH_USER_MODEL, verbose_name='استاد درس'),
        ),
        migrations.AddField(
            model_name='course_score',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='course_module.course', verbose_name='نمره ربوط به کدام درس می باشد'),
        ),
        migrations.AddField(
            model_name='course_score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='این نمره مربوط به کدام دانشجو می باشد'),
        ),
        migrations.AddConstraint(
            model_name='course_score',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='check score uniquness', violation_error_message='رکورد نمره این دانشجو برای این درس قبلا ایجاد شده است'),
        ),
    ]
