# Generated by Django 5.1.6 on 2025-08-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_times',
            name='day_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class_times',
            name='time_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
