# Generated by Django 5.1.6 on 2025-08-28 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_class_times_day_index_class_times_time_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ امتحان')),
                ('time', models.DateField(verbose_name='ساعت امتحان')),
                ('duration', models.IntegerField(verbose_name='مدت زمان تقریبی امتحان')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='exam_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_module.exam_times', verbose_name='تاریخ امتحان'),
        ),
    ]
