# Generated by Django 5.1.6 on 2025-08-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0004_exam_times_course_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان امتحان'),
        ),
        migrations.DeleteModel(
            name='Exam_Times',
        ),
    ]
