# Generated by Django 5.1.6 on 2025-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0005_alter_course_exam_time_delete_exam_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='changes_history',
            field=models.JSONField(blank=True, null=True, verbose_name='تاریخچه تغییرات درس'),
        ),
    ]
