# Generated by Django 5.1.6 on 2025-10-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0006_course_changes_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن اعتراض')),
                ('score', models.OneToOneField(error_messages={'null': 'این فیلد نمی تواند خالی باشد'}, on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='course_module.course_score', verbose_name='این اعتراض برای کدام نمره نوشته شده است')),
            ],
        ),
    ]
