# Generated by Django 5.1.6 on 2025-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0007_score_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_appeal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت اعتراض'),
        ),
    ]
