# Generated by Django 5.1.6 on 2025-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='زمان شروع ترم')),
                ('end_date', models.DateField(verbose_name='زمان پایان ترم')),
                ('semester_type', models.CharField(choices=[('تابستان', 'تابستان'), ('عادی', 'عادی')], default='عادی', max_length=30, verbose_name='نوع ترم')),
            ],
        ),
    ]
