# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='زمان شروع ترم')),
                ('end_date', models.DateField(verbose_name='زمان پایان ترم')),
                ('semester_type', models.CharField(choices=[('تابستان', 'تابستان'), ('عادی', 'عادی')], default='عادی', max_length=30, verbose_name='نوع ترم')),
                ('semester_status', models.CharField(choices=[('شروع نشده', 'شروع نشده'), ('انتخاب واحد', 'انتخاب واحد'), ('جاری', 'جاری'), ('امتحان', 'امتحان'), ('بسته', 'بسته')], default='شروع نشده', max_length=40, verbose_name='وضعیت ترم')),
            ],
        ),
        migrations.CreateModel(
            name='Current_Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester_module.semester')),
            ],
        ),
    ]
