# Generated by Django 5.1.6 on 2025-08-07 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester_module.semester')),
            ],
        ),
    ]
