# Generated by Django 5.1.6 on 2025-08-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester_module', '0002_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_status',
            field=models.CharField(choices=[('شروع نشده', 'شروع نشده'), ('انتخاب واحد', 'انتخاب واحد'), ('جاری', 'جاری'), ('امتحان', 'امتحان'), ('بسته', 'بسته')], default='شروع نشده', max_length=40, verbose_name='وضعیت ترم'),
        ),
    ]
