# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
import exam_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت پاسخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات مربوط به امتحان (اختیاری)')),
                ('file', models.FileField(upload_to='students_answerss', validators=[exam_module.models.exam_file_validator], verbose_name='فایل پاسخنامه')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع امتحان')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان امتحان')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='course_module.course', verbose_name='این امتحان مربوط به کدام درس می باشد')),
            ],
        ),
    ]
