# Generated by Django 5.1.6 on 2025-09-28 20:25

import django.db.models.deletion
import exam_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_module', '0006_course_changes_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع امتحان')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان امتحان')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='course_module.course', verbose_name='این امتحان مربوط به کدام درس می باشد')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت پاسخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات مربوط به امتحان (اختیاری)')),
                ('file', models.FileField(upload_to='', validators=[exam_module.models.exam_file_validator], verbose_name='فایل پاسخنامه')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_answers', to=settings.AUTH_USER_MODEL, verbose_name='کدام دانشجو پاسخ را ایجاد کرده است')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_module.exam', verbose_name='این پاسخ مربوط به کدام امتحان می باشد')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'exam'), name='author and exam uniquness', violation_error_message='این دانشجو قبلا برای این درس پاسخ ارسال کرده است')],
            },
        ),
    ]
