# Generated by Django 5.1.6 on 2025-10-04 03:55

import exam_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_answer',
            name='file',
            field=models.FileField(upload_to='students_answerss', validators=[exam_module.models.exam_file_validator], verbose_name='فایل پاسخنامه'),
        ),
    ]
