# Generated by Django 5.1.6 on 2025-11-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_answers', to=settings.AUTH_USER_MODEL, verbose_name='کدام دانشجو پاسخ را ایجاد کرده است'),
        ),
        migrations.AddField(
            model_name='exam_answer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam_module.exam', verbose_name='این پاسخ مربوط به کدام امتحان می باشد'),
        ),
        migrations.AddConstraint(
            model_name='exam_answer',
            constraint=models.UniqueConstraint(fields=('author', 'exam'), name='author and exam uniquness', violation_error_message='این دانشجو قبلا برای این درس پاسخ ارسال کرده است'),
        ),
    ]
